### ISSUE TITLE
Snapdragon x Elite Support Device Tree

### ISSUE THREAD

**Issue by denari94** [edk2-porting/linux-next#1]
I saw that you got a branch working on Device Trees for the Snapdragon X Elite devices.
I got the new Surface pro 11 and tested out the kernel. The Keyboard and USB Keyboards do not seem to work right now.

Is there any way i can help?
Are there any information i can provide that would help getting the Surface Devicetree working?
Any data out of the Device manager or HWinfo maybe?

**Comment by strongtz** [comment]
The internal keyboard isn't supposed to work now, but USB keyboard should work. What kernel config are you using? What state can the device boot to now?

**Comment by denari94** [comment]
USB Keyboards also do not seem to work.
In a modified debian install i get to the language selection, but since the Keyboards wont work not any further.
For testing i created a busybox image.
I get the Following output when i boot that.
![20240625_033142](https://github.com/edk2-porting/linux-next/assets/19516552/414aef1d-1553-41e6-a44e-1fc5c15cefd5)

**Comment by denari94** [comment]
It seems to detect some HID device, but when its done booting, i can not interact with it in any way.

**Comment by strongtz** [comment]
But what kernel config are you using? You should use the [x1e80100_defconfig](https://github.com/edk2-porting/linux-next/blob/work/sakuramist-x1e80100/arch/arm64/configs/x1e80100_defconfig)

**Comment by denari94** [comment]
Ah, damn now i feel stupid.
That was totally it. I just recompiled it and now it works.
You are a legend, thanks a lot.
